### ISSUE TITLE
Improve scripts to allow new PG versions

### ISSUE THREAD

**Issue by k-rus** [timescale/timescaledb-docker#107]
The main docker script is designed to work for existing PG version, since it requires previous docker image. This doesn't work when images are created the first time for new PG version, since no images were created.
It is good to generalise the scripts. Next PG version will PG 13.

**Comment by k-rus** [comment]
For PG 13 it was worked around it in [PG13 branch](https://github.com/timescale/timescaledb-docker/tree/pg13) by removing problematic code in the dockerfile in [this commit](https://github.com/timescale/timescaledb-docker/commit/0d4e92ac23d3a0d96c945a93f2130c159b2170ea).

**Comment by mkindahl** [comment]
The docker script build new images by copying data from old images seriously broken:

1. If something breaks with one image, we will just copy it forward anyway. There is no good way to eliminate bad builds.
2. If a mistake is made in one image and we end up with a duplicate file, it will just silently be overwritten.
3. It is evident that bootstrapping new images are broken (this is why this issue is raised).

We should:
1. Have packages for each version that we want to install.
2. Create a docker image with the correct PostgreSQL version and OS version.
3. Install the packages using the package installation tool (`apt`, `apk`, `yum`, `dnf`, whatever).

**Comment by k-rus** [comment]
@mkindahl The reason for older versions in the package is to allow a user to upgrade TimescaleDB. The current approach is not the best, however the suggestion with using packaging is not user friendly for this case.

**Comment by mkindahl** [comment]
@k-rus As we discussed on slack, this proposal is about making sure that we have a package for each installed version rather than copying them from previous images. It is not about changing the number of versions installed in an image and should therefore not affect the user from this view. The only difference would be that a user can remove versions that are not used in a familiar manner and install new package versions in a deployed docker image.

**Comment by svenklemm** [comment]
done as part of adding PG14 support
