### ISSUE TITLE
timescaledb-postgis:1.7.3-pg12 errors

### ISSUE THREAD

**Issue by tkald** [timescale/timescaledb-docker#113]
After installing timescaledb-postgis:1.7.3-pg12 over 1.7.2-pg12 i'm getting error:

`ERROR:  could not access file "$libdir/timescaledb-1.7.2": No such file or directory`

And I'm unable to connect postgres service on container

**Comment by k-rus** [comment]
@tkald Thank you for reporting. Have you updated your database with TimescaleDB to the new version? E.g.:
```sql
ALTER EXTENSION timescaledb UPDATE;
```
See https://docs.timescale.com/latest/using-timescaledb/update-db

**Comment by tkald** [comment]
postgres didn't start with timescaledb-postgis:1.7.3-pg12 container.
but latest timescaledb-postgis:1.7.4-pg12 version works as expected

**Comment by snspinn** [comment]
Maybe it's because I'm a timescale noob, but the insturctions on the "Updating a TimescaleDB Docker installation" [here](https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/updating-docker/#updating-a-timescaledb-docker-installation) threw me off a bit (see step 5).

Perhaps the commands should read:
```
docker exec -it timescaledb psql -U postgres -X <your_db_name>

# within the PostgreSQL instance
ALTER EXTENSION timescaledb UPDATE;
```

Otherwise, the command runs sucessfully but may miss the database the user is actually interested in.
